package bestroomie.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;

import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

import bestroomie.controller.BRAbstractController;
import bestroomie.util.BRConst;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
*
* @author aniu-lei
*/
public class BRMainGui extends BRAbstractView {

   /**
    * Creates new form BRMainGui
    */
   public BRMainGui() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       headPanel = new javax.swing.JPanel();
       settingBtn = new javax.swing.JButton();
       groupPnl = new javax.swing.JPanel();
       grpMemberPnl = new javax.swing.JPanel();
       jPanel4 = new javax.swing.JPanel();
       mainTab = new javax.swing.JTabbedPane();
       billPanel = new javax.swing.JPanel();
       jScrollPane4 = new javax.swing.JScrollPane();
       tbdBillTbl = new javax.swing.JTable();
       jScrollPane5 = new javax.swing.JScrollPane();
       oldBillTbl = new javax.swing.JTable();
       addBillBtn = new javax.swing.JButton();
       chorePanel = new javax.swing.JPanel();
       jScrollPane1 = new javax.swing.JScrollPane();
       tbdChoresTbl = new javax.swing.JTable();
       jScrollPane2 = new javax.swing.JScrollPane();
       oldChoresTbl = new javax.swing.JTable();
       addChoreBtn = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       headPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       settingBtn.setText("Settings");

       javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
       headPanel.setLayout(headPanelLayout);
       headPanelLayout.setHorizontalGroup(
           headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headPanelLayout.createSequentialGroup()
               .addGap(0, 0, Short.MAX_VALUE)
               .addComponent(settingBtn))
       );
       headPanelLayout.setVerticalGroup(
           headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(settingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
       );

       groupPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       javax.swing.GroupLayout groupPnlLayout = new javax.swing.GroupLayout(groupPnl);
       groupPnl.setLayout(groupPnlLayout);
       groupPnlLayout.setHorizontalGroup(
           groupPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 135, Short.MAX_VALUE)
       );
       groupPnlLayout.setVerticalGroup(
           groupPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 113, Short.MAX_VALUE)
       );

       grpMemberPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       javax.swing.GroupLayout grpMemberPnlLayout = new javax.swing.GroupLayout(grpMemberPnl);
       grpMemberPnl.setLayout(grpMemberPnlLayout);
       grpMemberPnlLayout.setHorizontalGroup(
           grpMemberPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 135, Short.MAX_VALUE)
       );
       grpMemberPnlLayout.setVerticalGroup(
           grpMemberPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 0, Short.MAX_VALUE)
       );

       tbdBillTbl.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null}
           },
           new String [] {
               "Title 1", "Title 2", "Title 3", "Title 4"
           }
       ));
       jScrollPane4.setViewportView(tbdBillTbl);

       oldBillTbl.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null}
           },
           new String [] {
               "Title 1", "Title 2", "Title 3", "Title 4"
           }
       ));
       jScrollPane5.setViewportView(oldBillTbl);

       addBillBtn.setText("Add a bill");

       javax.swing.GroupLayout billPanelLayout = new javax.swing.GroupLayout(billPanel);
       billPanel.setLayout(billPanelLayout);
       billPanelLayout.setHorizontalGroup(
           billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(billPanelLayout.createSequentialGroup()
                       .addGap(0, 185, Short.MAX_VALUE)
                       .addComponent(addBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
               .addContainerGap())
           .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(billPanelLayout.createSequentialGroup()
                   .addContainerGap()
                   .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                   .addContainerGap()))
       );
       billPanelLayout.setVerticalGroup(
           billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billPanelLayout.createSequentialGroup()
               .addContainerGap(117, Short.MAX_VALUE)
               .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(addBillBtn)
               .addGap(22, 22, 22))
           .addGroup(billPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(billPanelLayout.createSequentialGroup()
                   .addGap(10, 10, 10)
                   .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(163, Short.MAX_VALUE)))
       );

       mainTab.addTab("Bill", billPanel);

       tbdChoresTbl.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null}
           },
           new String [] {
               "Title 1", "Title 2", "Title 3", "Title 4"
           }
       ));
       jScrollPane1.setViewportView(tbdChoresTbl);

       oldChoresTbl.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null},
               {null, null, null, null}
           },
           new String [] {
               "Title 1", "Title 2", "Title 3", "Title 4"
           }
       ));
       jScrollPane2.setViewportView(oldChoresTbl);

       addChoreBtn.setText("Add a Chore");

       javax.swing.GroupLayout chorePanelLayout = new javax.swing.GroupLayout(chorePanel);
       chorePanel.setLayout(chorePanelLayout);
       chorePanelLayout.setHorizontalGroup(
           chorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(chorePanelLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(chorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(addChoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(15, Short.MAX_VALUE))
           .addGroup(chorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(chorePanelLayout.createSequentialGroup()
                   .addContainerGap()
                   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(15, Short.MAX_VALUE)))
       );
       chorePanelLayout.setVerticalGroup(
           chorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chorePanelLayout.createSequentialGroup()
               .addContainerGap(118, Short.MAX_VALUE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(addChoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
           .addGroup(chorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(chorePanelLayout.createSequentialGroup()
                   .addGap(10, 10, 10)
                   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(164, Short.MAX_VALUE)))
       );

       mainTab.addTab("Chores", chorePanel);

       javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
       jPanel4.setLayout(jPanel4Layout);
       jPanel4Layout.setHorizontalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel4Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(mainTab))
       );
       jPanel4Layout.setVerticalGroup(
           jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(mainTab)
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(headPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(grpMemberPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(groupPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(groupPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(grpMemberPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addContainerGap())
       );

       pack();
       setLocationRelativeTo(null);
       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
   }// </editor-fold>                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(BRMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(BRMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(BRMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(BRMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

//       /* Create and display the form */
//       java.awt.EventQueue.invokeLater(new Runnable() {
//           public void run() {
//               new BRMainGui().setVisible(true);
//           }
//       });
       new BRMainGui().setVisible(true);
       
   }

   // Variables declaration - do not modify                     
   private javax.swing.JButton settingBtn;
   private javax.swing.JButton addBillBtn;
   private javax.swing.JButton addChoreBtn;
   private javax.swing.JPanel headPanel;
   private javax.swing.JPanel groupPnl;
   private javax.swing.JPanel grpMemberPnl;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel billPanel;
   private javax.swing.JPanel chorePanel;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane4;
   private javax.swing.JScrollPane jScrollPane5;
   private javax.swing.JTabbedPane mainTab;
   private javax.swing.JTable tbdChoresTbl;
   private javax.swing.JTable oldChoresTbl;
   private javax.swing.JTable tbdBillTbl;
   private javax.swing.JTable oldBillTbl;
   // End of variables declaration                   
	@Override
	public void registerListener(BRAbstractController a) {
		// TODO Auto-generated method stub
		
	}
}
